FROM alpine

ARG TARGETPLATFORM
ENV TZ=Asia/Shanghai

RUN apk add --no-cache alpine-conf ca-certificates curl && \
    /usr/sbin/setup-timezone -z Asia/Shanghai && \
    apk del alpine-conf && \
    rm -rf /var/cache/apk/* &&\
    mkdir -p /opt

COPY docker/musl/${TARGETPLATFORM}/bestsub /opt/bestsub
COPY entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]